name: 'eonx-labs/actions-opsgenie-alert'
description: 'Send an alert using OpsGenie API V2'
author: 'Damian Sloane <damian.sloane@eonx.com>'

branding:
  icon: 'x'
  color: 'red'

inputs:
  alias:
    description: 'Unique identifier for this type of alert (used to de-duplicate alerts)'
    required: true
  priority:
    description: 'Alert priority level (one of the P1-P5 OpsGenie alert levels)'
    required: true
  message:
    description: 'Message to attach to the alert'
    required: true
  api_key:
    description: 'OpsGenie API Key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.message }}
    - ${{ inputs.priority }}
    - ${{ inputs.api_key }}